Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName PresentationCore
$Root=Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$Ready=Join-Path $Root 'launcher\.ready';$ErrorFile=Join-Path $Root 'launcher\.error';$StatusFile=Join-Path $Root 'launcher\.status';$Log=Join-Path $Root 'launcher\launcher.log'
[xml]$xaml=@"
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" WindowStyle="None" ResizeMode="NoResize" WindowStartupLocation="CenterScreen" Width="560" Height="320" Background="Transparent" AllowsTransparency="True" Topmost="True"><Border CornerRadius="24" BorderThickness="1" BorderBrush="#7D42FF" Background="#0E0A1A" Padding="34"><Grid><Grid.RowDefinitions><RowDefinition Height="*"/><RowDefinition Height="Auto"/></Grid.RowDefinitions><StackPanel VerticalAlignment="Center" HorizontalAlignment="Center"><TextBlock Text="SPEED" Foreground="White" FontSize="44" FontWeight="Bold" HorizontalAlignment="Center"/><TextBlock Text="VAGAS PRO" Foreground="#B98CFF" FontSize="22" FontWeight="SemiBold" HorizontalAlignment="Center" Margin="0,2,0,18"/><TextBlock Name="StatusText" Text="Iniciando aplicativo..." Foreground="#C8C4D4" FontSize="14" Width="430" TextAlignment="Center" TextWrapping="Wrap"/><ProgressBar Name="Progress" IsIndeterminate="True" Width="330" Height="6" Margin="0,20,0,0" Background="#21182E" Foreground="#9B5CFF"/><StackPanel Name="ErrorButtons" Orientation="Horizontal" HorizontalAlignment="Center" Margin="0,18,0,0" Visibility="Collapsed"><Button Name="OpenLog" Content="Ver detalhes" Width="110" Height="30" Margin="0,0,10,0"/><Button Name="CloseButton" Content="Fechar" Width="90" Height="30"/></StackPanel></StackPanel><TextBlock Grid.Row="1" Text="SPEED VAGAS PRO 6.4" Foreground="#6F687C" FontSize="11" HorizontalAlignment="Center"/></Grid></Border></Window>
"@
$reader=New-Object System.Xml.XmlNodeReader $xaml;$window=[Windows.Markup.XamlReader]::Load($reader);$status=$window.FindName('StatusText');$progress=$window.FindName('Progress');$errorButtons=$window.FindName('ErrorButtons');$openLog=$window.FindName('OpenLog');$closeButton=$window.FindName('CloseButton')
$openLog.Add_Click({if(Test-Path $Log){Start-Process notepad.exe $Log}});$closeButton.Add_Click({$window.Close()})
$startedAt=Get-Date;$timer=New-Object Windows.Threading.DispatcherTimer;$timer.Interval=[TimeSpan]::FromMilliseconds(300);$timer.Add_Tick({if(Test-Path $StatusFile){try{$txt=Get-Content $StatusFile -Raw -ErrorAction SilentlyContinue;if($txt){$status.Text=$txt.Trim()}}catch{}};if(Test-Path $ErrorFile){$timer.Stop();$progress.IsIndeterminate=$false;$progress.Value=0;try{$err=Get-Content $ErrorFile -Raw -ErrorAction SilentlyContinue;$status.Text=$err.Trim()}catch{$status.Text='Falha ao iniciar o aplicativo.'};$status.Foreground='#FFB4B4';$errorButtons.Visibility='Visible'}elseif(Test-Path $Ready){$timer.Stop();$status.Text='Pronto!';Start-Sleep -Milliseconds 350;$window.Close()}elseif(((Get-Date)-$startedAt).TotalMinutes -ge 10){$timer.Stop();$progress.IsIndeterminate=$false;$progress.Value=0;$status.Text='A inicializacao demorou mais que o esperado. Clique em Ver detalhes para consultar o log.';$status.Foreground='#FFB4B4';$errorButtons.Visibility='Visible'}});$timer.Start();$window.ShowDialog()|Out-Null
